name: Azure App Deploy

on:
  push:

jobs:
  DEPLOY-PHP:
    name: Setup project
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@master

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUB_PROFILE }}
          package: "."

      - name: Set up ssh key
        env:
          SSH_HOME: .ssh
        run: |
          mkdir -p ${{ env.SSH_HOME }}
          echo "${{ secrets.AZURE_SSH_PRV_KEY }}" > ${{ env.SSH_HOME }}/id_rsa
          echo "${{ secrets.AZURE_SSH_PUB_KEY }}" > ${{ env.SSH_HOME }}/id_rsa.pub
          chmod 400 -R ${{ env.SSH_HOME }}
        shell: bash

      - name: Run ssh command
        env:
          SSH_PASSWORD: "Docker!"
          SSH_PORT: 6007
          WAIT_TIME: 5
        run: |
          az login --service-principal --username '${{ secrets.SP_USERNAME }}' --tenant '${{ secrets.SP_TENANT }}' --password '${{ secrets.SP_PASSWORD }}'

          sleep ${{ env.WAIT_TIME }}
        
          az webapp create-remote-connection --subscription '${{ env.APP_SUBSCRIPTION }}' --resource-group ${{ secrets.APP_RS_GROUP }} -n ${{env.APP_NAME }} --port ${{ env.SSH_PORT }} &
       
          sleep ${{ env.WAIT_TIME }}

          sshpass -p ${{env.SSH_PASSWORD}} ssh -o StrictHostKeyChecking=no root@127.0.0.1 -p ${{ env.SSH_PORT }} "ls -a"
        shell: bash